version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - //c/Users/admin/.ollama/models:/app/models
    networks:
      - pc-doc-net  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pc-doc-net

networks:
  pc-doc-net:
    driver: bridge
