version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - chromadb

  chromadb:
    image: python:3.8-slim
    working_dir: /app
    command: chroma run --host 0.0.0.0 --port 8000 --path chromadb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
