services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      CHROMADB_HOST: chromadb
      CHROMADB_PORT: 8001
    depends_on:
      - chromadb

  chromadb:
    image: python:3.8-slim
    working_dir: /app
    command: chroma run --host 0.0.0.0 --port 8001 --path chromadb
    ports:
      - "8001:8001"  
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
